model = "F5TTS_v1_Base"

ref_audio = "aman.wav"

ref_text = "You know, sorry collapse them in like this and it might be easier. Now if let's say you wanna find a specific"

gen_text = "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring."

gen_file = ""

remove_silence = false

output_dir = "./"

output_file = "infer_cli_basic.wav"
